services:
  groshi:
    container_name: groshi
    build:
      context: ./groshi/

    environment:
      GROSHI_HOST: 0.0.0.0
      GROSHI_PORT: 8080
      GROSHI_SWAGGER: true
      GROSHI_DEBUG: false

      GROSHI_JWT_SECRET_KEY_FILE: /run/secrets/groshi/jwt_secret_key
      GROSHI_EXCHANGERATES_API_KEY: /run/secrets/groshi/exchangerates_api_key

      GROSHI_MONGO_HOST: groshi-mongo
      GROSHI_MONGO_PORT: 27017
      GROSHI_MONGO_USERNAME_FILE: /run/secrets/groshi-mongo/username
      GROSHI_MONGO_PASSWORD_FILE: /run/secrets/groshi-mongo/password
      GROSHI_MONGO_DATABASE_FILE: /run/secrets/groshi-mongo/database

    depends_on:
      - groshi-mongo

    secrets:
      - groshi
      - groshi-mongo

  groshi-mongo:
    container_name: groshi-mongo
    image: mongo
    # restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/groshi-mongo/username
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/groshi-mongo/password
      MONGO_INITDB_DATABASE_FILE: /run/secrets/groshi-mongo/database

    volumes:
      - ./groshi/.mongo:/data/db

    secrets:
      - groshi-mongo

  webgroshi:
    container_name: webgroshi
    build:
        context: ./webgroshi/
        args:
            GROSHI_SOCKET: http://localhost/api

  groshi-website-nginx:
    image: nginx
    container_name: groshi-website-nginx
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"
    depends_on:
      - groshi
      - groshi-mongo

secrets:
  groshi:
    file: ./groshi/.secrets/groshi

  groshi-mongo:
    file: ./groshi/.secrets/groshi-mongo
